name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run tests on ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux-64
            runner: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: latest
          # Enable caching of the pixi environment
          cache: true
          # Only write to cache on main branch for efficiency
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Build scikit-learn documentation
        run: pixi run -e preamble build-doc-sklearn

      - name: Run tests
        run: pixi run -e tests tests
